- name: backend setup
  hosts: all
  become: true
  tasks:
    - name: disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable nodejs 20v
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Add user
      ansible.builtin.user:
        name: expense

    - name: Clean the Old Content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: make a directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download and extract backend content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Download Nodejs dependencies
      community.general.npm:
        path: /app
        state: latest

    - name: copy backend.service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start MySQL Service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install Python MySQL Client
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: pip3.11

    - name: Load schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql-dev.angadicnc.online

    - name: start backend service
      ansible.builtin.systemd_service:
        name: backend
        daemon_reload: yes
        state: restarted
        enabled: yes
