- name: mysql setup
  hosts: all
  become: true
  tasks:

    - name: install mysql
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: start mysql service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: set mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

