- name: install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: Install Python MySQL Client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.11

- name: check the db connection with our password
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.angadicnc.online
    filter: version
    register: mysql_connection_output

- name: print
  debug:
    msg: "{{ mysql_connection_output }}"

- name: set mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
  when: mysql_connection_output.failed is true
