- name: install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Install Python MySQL Client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.11

- name: start mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: set mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

