format_version: 10
pipelines:
  frontend:
    group: defaultGroup
    materials:
      git-1c78e63:
        git: https://github.com/Nageshadevops/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Dev:
          fetch_materials: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash #bash ansible.sh frontend
                    run_if: passed
      - QA:
          fetch_materials: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash #bash ansible.sh frontend
                    run_if: passed
      - Stage:
          fetch_materials: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash #bash ansible.sh frontend
                    run_if: passed
      - PROD:
          fetch_materials: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash #bash ansible.sh frontend
                    run_if: passed

