- name: Set Prompt with component
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: Install Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    task_from: node_exporter